### PR TITLE
README.rst: Fix rendering on PyPI

### PR DESCRIPTION
**Pull request by msabramo**
You can't use a local file for an image on PyPI; it has to be a URL I think.

Merge this and then do `python setup.py register` to update the PyPI description.

### CODE REVIEW

**Comment by bmcorser** [comment]
Cheers https://pypi.python.org/pypi/bade :)

**Comment by msabramo** [comment]
Cool!

You may want to vote on this issue: https://bitbucket.org/pypa/pypi/pull-request/60/fix-bb-214-make-rst-rendering-not-fail-for/diff

**Comment by bmcorser** [comment]
I think I'd rather have the tools to correct it before I upload (setup.py
check is broken / not widely documented) but sure, I'll vote :)

**Comment by msabramo** [comment]
Agreed about having tools to correct it. They are broken. See http://bugs.python.org/issue23063 -- trying to get a core developer to review it.

The most reliable way I have found to find reST problems is to use [restview](http://bugs.python.org/issue23063):

```
pip install restview
restview --pypi-strict README.rst
```

**Comment by bmcorser** [comment]
Looks useful, thanks.

BTW, if you're thinking of actually using bade I'm working on making the CSS not look so awful out of the box. I'll hurry that along if I've got a customer :wink:

**Pull request merged**
